### ISSUE TITLE
Serch error

### ISSUE THREAD

**Issue by GregMage** [XoopsModules25x/extcal#26] opened 2020-06-30 19:48 UTC
Avertissement: cal_days_in_month(): invalid date dans le fichier /modules/extcal/view_search.php ligne 99

**Comment by GregMage** [comment] 2020-06-30 19:50
1 events found  but not listed

**Comment by cesagonchu** [comment] 2020-07-01 01:15
I wanted to inform you that maybe the translation has something to do with this error.
I translated the English date into French date:

`l dS of F Y h:i:s A`

translated into

`l j F Y à H:i:s`

I think the problematic file, because it is not in the language files is the pcltar.lib.php file
because it contains 7 times the date format in English:

extcal\class\pcltar.lib.php (Line 2105; 2617; 3137; 3138; 3428)

TrFctMessage(__FILE__, __LINE__, 2, "Existing file ".$v_header['filename']." is newer (".date("l dS of F Y h:i:s A", filemtime($v_header['filename'])).") than the extracted file (".date("l dS of F Y h:i:s A", $v_header['mtime']).")");
            TrFctMessage(__FILE__, __LINE__, 2, "Existing file ".$v_header['filename']." is newer (".date("l dS of F Y h:i:s A", filemtime($v_header['filename'])).") than the extracted file (".date("l dS of F Y h:i:s A", $v_header['mtime']).")");
                        TrFctMessage(__FILE__, __LINE__, 2, 'Existing file ' . $v_header['filename'] . ' is newer (' . date('l dS of F Y h:i:s A', filemtime($v_header['filename'])) . ') than the extracted file (' . date('l dS of F Y h:i:s A', $v_header['mtime']) . ')');
                        TrFctMessage(__FILE__, __LINE__, 2, 'Existing file ' . $v_header['filename'] . ' is newer (' . date('l dS of F Y h:i:s A', filemtime($v_header['filename'])) . ') than the extracted file (' . date('l dS of F Y h:i:s A', $v_header['mtime']) . ')');
                    TrFctMessage(__FILE__, __LINE__, 3, "File '$v_stored_list[$i]' mtime=" . filemtime($p_file_list[$i]) . ' ' . date('l dS of F Y h:i:s A', filemtime($p_file_list[$i])));
                    TrFctMessage(__FILE__, __LINE__, 3, 'Archived mtime=' . $v_header['mtime'] . ' ' . date('l dS of F Y h:i:s A', $v_header['mtime']));
        TrFctMessage(__FILE__, __LINE__, 2, 'Date : ' . date('l dS of F Y h:i:s A', $v_header['mtime']));



___
Location of modified files:

FR
extcal\language\french\main.php Line 102
`define('_MD_EXTCAL_FORMAT_DATE', 'l j F Y à H:i:s');`

extcal\language\french\modinfo.php Line 51
`define('_MI_EXTCAL_EE_DATE_PATTERN_VALUE', "l j F Y à H:i:s");`


EN
extcal\language\english\main.php
define('_MD_EXTCAL_FORMAT_DATE', 'l dS of F Y h:i:s A');

extcal\language\english\modinfo.php
define('_MI_EXTCAL_EE_DATE_PATTERN_VALUE', "l dS \of F Y h:i A");

**Comment by GregMage** [comment] 2020-07-01 08:05
Hi Christelle,

I do not use the translation fr for my tests, for the moment I am in English. So the problem is not a translation problem ...

**Comment by GregMage** [comment] 2020-07-01 08:06
Warning: cal_days_in_month(): invalid date in file /modules/extcal/view_search.php line 100

**Comment by mambax7** [comment] 2020-07-09 01:42
How is your XOOPS setup - does it use French language?

**Comment by mambax7** [comment] 2020-07-09 04:40
I can't reproduce it here:
![image](https://user-images.githubusercontent.com/613686/86997701-b67d6c80-c17c-11ea-9341-3354ca3297a0.png)

Please reopen, if you could provide me with steps to reproduce it

**Comment by GregMage** [comment] 2020-07-09 08:28
![Uploading image.png…]()

**Comment by mambax7** [comment] 2020-07-09 11:11
Fixed in: https://github.com/XoopsModules25x/extcal/pull/36

**Closed by mambax7** 2020-07-09 11:11 UTC
